#!/usr/bin/env python3
"""
WuK SITL Data Visualization Tool v2.0

Features:
1. Read CSV file generated by wuk_analyzer.cpp
2. Generate 4 analysis charts:
   - Chart 1: Motor thrust direction tilt relative to body roll axis
   - Chart 2: Motor thrust direction and attitude relative to world roll axis
   - Chart 3: Motor thrust, total thrust and vertical thrust component
   - Chart 4: Altitude change
3. Mark morph start time and rapid descent events

Dependencies: matplotlib, numpy, pandas
"""

import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

# Font configuration
plt.rcParams['font.sans-serif'] = ['DejaVu Sans', 'Arial']
plt.rcParams['axes.unicode_minus'] = False

def load_data(csv_file):
    """Load CSV data"""
    try:
        df = pd.read_csv(csv_file)
        print(f"✓ Successfully loaded data: {len(df)} data points")
        return df
    except Exception as e:
        print(f"✗ Failed to load CSV file: {e}")
        sys.exit(1)

def detect_events(df):
    """Detect key events"""
    events = {
        'morph_start': None,
        'altitude_drop': None
    }
    
    # Morph start event (first time morph_start == 1)
    morph_start_idx = df[df['morph_start'] == 1].index
    if len(morph_start_idx) > 0:
        events['morph_start'] = df.loc[morph_start_idx[0], 'time_s']
        print(f"✓ Detected morph start: {events['morph_start']:.2f} seconds")
    else:
        print("⚠ Morph start event not detected")
    
    # Rapid altitude drop event
    drop_idx = df[df['altitude_drop'] == 1].index
    if len(drop_idx) > 0:
        events['altitude_drop'] = df.loc[drop_idx[0], 'time_s']
        print(f"✓ Detected altitude drop: {events['altitude_drop']:.2f} seconds")
    else:
        print("✓ No altitude drop detected (altitude control stable)")
    
    return events

def plot_data(df, events, output_file='wuk_analysis.png'):
    """Generate 4 analysis charts"""
    
    fig = plt.figure(figsize=(16, 14))
    gs = gridspec.GridSpec(4, 1, height_ratios=[1, 1, 1, 1], hspace=0.35)
    
    time_s = df['time_s'].values
    
    # === Chart 1: Motor Tilt Angle Relative to Body Roll Axis ===
    ax1 = fig.add_subplot(gs[0])
    
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728']
    for i in range(4):
        col_name = f'm{i+1}_tilt_body'
        ax1.plot(time_s, df[col_name], label=f'M{i+1} Tilt', 
                linewidth=1.8, alpha=0.85, color=colors[i])
    
    # Mark events
    if events['morph_start']:
        ax1.axvline(x=events['morph_start'], color='red', linestyle=':', 
                   linewidth=2.5, alpha=0.7, label='Morph Start')
    if events['altitude_drop']:
        ax1.axvline(x=events['altitude_drop'], color='orange', linestyle='--', 
                   linewidth=2.5, alpha=0.7, label='Altitude Drop')
    
    ax1.axhline(y=0, color='gray', linestyle=':', linewidth=1, alpha=0.5)
    ax1.axhline(y=45, color='purple', linestyle='--', linewidth=1, alpha=0.5, 
               label='Target 45deg')
    ax1.axhline(y=90, color='brown', linestyle='--', linewidth=1, alpha=0.5, 
               label='GROUND 90deg')
    
    ax1.set_xlabel('Time (s)', fontsize=11, fontweight='bold')
    ax1.set_ylabel('Tilt Angle (deg)', fontsize=11, fontweight='bold')
    ax1.set_title('Chart 1: Motor Thrust Direction Tilt Relative to Body Roll Axis', 
                 fontsize=13, fontweight='bold', pad=10)
    ax1.legend(loc='best', fontsize=9, ncol=3, framealpha=0.9)
    ax1.grid(True, alpha=0.3, linestyle='--')
    ax1.set_ylim(-5, 95)
    
    # === Chart 2: Motor Tilt and Attitude Relative to World Roll Axis ===
    ax2 = fig.add_subplot(gs[1])
    
    # Motor tilt angle (world frame)
    for i in range(4):
        col_name = f'm{i+1}_tilt_world'
        ax2.plot(time_s, df[col_name], label=f'M{i+1} World Tilt', 
                linewidth=1.5, alpha=0.7, color=colors[i], linestyle='-')
    
    # Body roll angle (world frame)
    ax2.plot(time_s, df['roll_deg'], label='Body Roll', 
            linewidth=2.5, color='black', linestyle='--', alpha=0.8)
    
    # Mark events
    if events['morph_start']:
        ax2.axvline(x=events['morph_start'], color='red', linestyle=':', 
                   linewidth=2.5, alpha=0.7)
    if events['altitude_drop']:
        ax2.axvline(x=events['altitude_drop'], color='orange', linestyle='--', 
                   linewidth=2.5, alpha=0.7)
    
    ax2.axhline(y=0, color='gray', linestyle=':', linewidth=1, alpha=0.5)
    
    ax2.set_xlabel('Time (s)', fontsize=11, fontweight='bold')
    ax2.set_ylabel('Angle (deg)', fontsize=11, fontweight='bold')
    ax2.set_title('Chart 2: Motor Thrust Direction and Attitude Relative to World Roll Axis', 
                 fontsize=13, fontweight='bold', pad=10)
    ax2.legend(loc='best', fontsize=9, ncol=3, framealpha=0.9)
    ax2.grid(True, alpha=0.3, linestyle='--')
    
    # === Chart 3: Motor Thrust, Total Thrust and Vertical Thrust ===
    ax3 = fig.add_subplot(gs[2])
    
    # Individual motor thrust
    for i in range(4):
        col_name = f'm{i+1}_thrust'
        ax3.plot(time_s, df[col_name], label=f'M{i+1} Thrust', 
                linewidth=1.5, alpha=0.7, color=colors[i])
    
    # Total thrust
    ax3.plot(time_s, df['total_thrust'], label='Total Thrust', 
            linewidth=2.5, color='black', linestyle='-', alpha=0.85)
    
    # Vertical thrust component
    ax3.plot(time_s, df['vertical_thrust'], label='Vertical Thrust', 
            linewidth=2.5, color='green', linestyle='--', alpha=0.85)
    
    # Mark events
    if events['morph_start']:
        ax3.axvline(x=events['morph_start'], color='red', linestyle=':', 
                   linewidth=2.5, alpha=0.7)
    if events['altitude_drop']:
        ax3.axvline(x=events['altitude_drop'], color='orange', linestyle='--', 
                   linewidth=2.5, alpha=0.7)
    
    ax3.set_xlabel('Time (s)', fontsize=11, fontweight='bold')
    ax3.set_ylabel('Thrust (N)', fontsize=11, fontweight='bold')
    ax3.set_title('Chart 3: Motor Thrust, Total Thrust and Vertical Thrust Component', 
                 fontsize=13, fontweight='bold', pad=10)
    ax3.legend(loc='best', fontsize=9, ncol=3, framealpha=0.9)
    ax3.grid(True, alpha=0.3, linestyle='--')
    
    # === Chart 4: Altitude Change ===
    ax4 = fig.add_subplot(gs[3])
    
    ax4.plot(time_s, df['altitude_m'], label='Altitude', 
            linewidth=2.5, color='#9467bd', alpha=0.85)
    ax4.fill_between(time_s, 0, df['altitude_m'], alpha=0.2, color='#9467bd')
    
    # Mark events
    if events['morph_start']:
        ax4.axvline(x=events['morph_start'], color='red', linestyle=':', 
                   linewidth=2.5, alpha=0.7, label='Morph Start')
    if events['altitude_drop']:
        ax4.axvline(x=events['altitude_drop'], color='orange', linestyle='--', 
                   linewidth=2.5, alpha=0.7, label='Altitude Drop')
    
    ax4.axhline(y=5.0, color='green', linestyle='--', linewidth=1, alpha=0.5, 
               label='Hover Reference (5m)')
    
    ax4.set_xlabel('Time (s)', fontsize=11, fontweight='bold')
    ax4.set_ylabel('Altitude (m)', fontsize=11, fontweight='bold')
    ax4.set_title('Chart 4: Altitude Change During Morphing', fontsize=13, fontweight='bold', pad=10)
    ax4.legend(loc='best', fontsize=9, ncol=2, framealpha=0.9)
    ax4.grid(True, alpha=0.3, linestyle='--')
    
    # Save figure
    plt.tight_layout()
    plt.savefig(output_file, dpi=200, bbox_inches='tight')
    print(f"\n✓ Chart saved: {output_file}")
    plt.close()

def print_summary(df, events):
    """Print analysis summary"""
    print("\n" + "="*70)
    print("=== Data Analysis Summary ===")
    print("="*70)
    
    print(f"\nTime range: {df['time_s'].min():.2f} - {df['time_s'].max():.2f} seconds")
    print(f"Data points: {len(df)}")
    
    print(f"\nFC angle range: {df['fc_angle'].min():.1f}° - {df['fc_angle'].max():.1f}°")
    
    print("\nAttitude change:")
    print(f"  Roll:  [{df['roll_deg'].min():.2f}°, {df['roll_deg'].max():.2f}°]")
    print(f"  Pitch: [{df['pitch_deg'].min():.2f}°, {df['pitch_deg'].max():.2f}°]")
    print(f"  Yaw:   [{df['yaw_deg'].min():.2f}°, {df['yaw_deg'].max():.2f}°]")
    
    print("\nMotor tilt angle change (body frame):")
    for i in range(4):
        col = f'm{i+1}_tilt_body'
        print(f"  M{i+1}: [{df[col].min():.2f}°, {df[col].max():.2f}°]")
    
    print("\nThrust statistics:")
    print(f"  Total thrust: [{df['total_thrust'].min():.2f}N, {df['total_thrust'].max():.2f}N]")
    print(f"  Vertical thrust: [{df['vertical_thrust'].min():.2f}N, {df['vertical_thrust'].max():.2f}N]")
    
    print("\nAltitude change:")
    print(f"  Altitude range: [{df['altitude_m'].min():.2f}m, {df['altitude_m'].max():.2f}m]")
    
    # Before/after morph comparison
    if events['morph_start']:
        morph_time = events['morph_start']
        pre_df = df[df['time_s'] < morph_time]
        post_df = df[df['time_s'] >= morph_time]
        
        if len(pre_df) > 0 and len(post_df) > 0:
            print("\nBefore/After morph comparison:")
            
            pre_thrust = pre_df['total_thrust'].mean()
            post_thrust = post_df['total_thrust'].mean()
            thrust_change = ((post_thrust - pre_thrust) / pre_thrust * 100) if pre_thrust > 0 else 0
            print(f"  Avg total thrust: {pre_thrust:.2f}N → {post_thrust:.2f}N ({thrust_change:+.1f}%)")
            
            pre_vthrust = pre_df['vertical_thrust'].mean()
            post_vthrust = post_df['vertical_thrust'].mean()
            vthrust_change = ((post_vthrust - pre_vthrust) / pre_vthrust * 100) if pre_vthrust > 0 else 0
            print(f"  Avg vertical thrust: {pre_vthrust:.2f}N → {post_vthrust:.2f}N ({vthrust_change:+.1f}%)")
            
            pre_alt = pre_df['altitude_m'].mean()
            post_alt = post_df['altitude_m'].mean()
            alt_change = post_alt - pre_alt
            print(f"  Avg altitude: {pre_alt:.2f}m → {post_alt:.2f}m ({alt_change:+.2f}m)")
    
    print("\nKey events:")
    if events['morph_start']:
        print(f"  ✓ Morph start: {events['morph_start']:.2f} seconds")
    else:
        print("  ✗ Morph start not detected")
    
    if events['altitude_drop']:
        print(f"  ⚠ Altitude drop: {events['altitude_drop']:.2f} seconds")
    else:
        print("  ✓ No altitude drop (altitude control stable)")
    
    print("="*70)

def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <input.csv> [output.png]")
        print(f"Example: {sys.argv[0]} wuk_analysis.csv wuk_plot.png")
        sys.exit(1)
    
    csv_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) >= 3 else 'wuk_analysis.png'
    
    print("=== WuK SITL Data Visualization Tool v2.0 ===")
    print(f"Input CSV: {csv_file}")
    
    # Load data
    df = load_data(csv_file)
    
    # Detect events
    events = detect_events(df)
    
    # Generate charts
    plot_data(df, events, output_file)
    
    # Print summary
    print_summary(df, events)
    
    print("\n✅ Visualization completed!")
    print(f"Output chart: {output_file}\n")
    
    print("📌 Chart description:")
    print("   - Red dashed line: Morph start time")
    print("   - Orange dashed line: Rapid altitude drop time")
    print("   - Chart 1: Motor tilt should change from 0° to 45° (MORPH) or 90° (GROUND)")
    print("   - Chart 2: Motor tilt (world) = Motor tilt (body) + Body roll angle")
    print("   - Chart 3: Total thrust should increase with tilt to compensate vertical loss")
    print("   - Chart 4: Altitude should remain stable (no rapid descent)\n")

if __name__ == '__main__':
    main()
